book-service:
  server: localhost
  port: 8081
  context-root: /order-book

translate-service:
  server: localhost
  port: 8082
  context-root: /translate

print-book-service:
  server: localhost
  port: 8083
  context-root: /print