server:
  port: 8081

# Binding health checks to a different port
management:
  port: 8081

route-service:
  server: localhost
  port: 8080
  context-root: /api/router/book-router

# disable all management end points except health
endpoints:
  enabled: false
  health:
    enabled: true

spring:
  h2:
    console:
      enabled: true